# Generated by Django 5.1.3 on 2024-11-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
    
